spring:
  application:
    name: akhs-configurations
  profiles:
    active: dev,native,git
  cloud:
    config:
      server:
        health:
          repositories:
            application:
              label: main
              profiles: dev,native,git
        git:
          uri: git@github.com:kiNgchev/akhs-configurations.git
          default-label: main
          ignoreLocalSshSettings: true
          strictHostKeyChecking: false
          private-key:
          passphrase:
          searchPaths: {application}
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: '*'